### ISSUE TITLE
Tags for older releases

### ISSUE THREAD

**Issue by technomancy** [supercollider/sc3-plugins#100]
I'm trying to build this code on Debian Jessie, which ships with Supercollider 3.6.6. I'm getting compilation failures(https://gist.github.com/technomancy/ad2c7081eb9e86d8f8f64ab73cfb6318), but I read that these could be solved by matching up the version of the plugins with the version of Supercollider.

Unfortunately I can't find what version to use since the releases before 3.7.0 were not properly tagged. Can you push tags for these versions or suggest another way to fix the compilation failure?

**Comment by snappizz** [comment]
That error indicates to me that you aren't using a modern version of the sc3-plugins source. The GET_BUF redefinition in TagSystemUGens was fixed [in 2013](https://github.com/supercollider/sc3-plugins/commit/cff2a7ce8faf82f7b34ee35612d0990775046b37).

**Comment by technomancy** [comment]
Thanks; I ended up solving it by simply deleting the offending plugins (`source/JoshUGens` and `source/NCAnalysisUGens`) and removing any mention of them from `source/CMakeLists.txt` instead.
