### ISSUE TITLE
BhobUGens: GaussTrig.kr outputs constant 1

### ISSUE THREAD

**Issue by snappizz** [supercollider/sc3-plugins#102]
Test case:

    { GaussTrig.ar(1000, 0.3) }.plot(0.01);
    { GaussTrig.kr(1000, 0.3) }.plot(0.01);

reported by mike parr-burman on the facebook group.

**Comment by telephon** [comment]
btw. `GaussTrig` is a bit of a misnomer, because you'd expect something like a trigger input. But well …

**Comment by snappizz** [comment]
hmm, this may be invalid. doesn't make sense to test a 1000 hz oscillator when my control frequency is only 689 hz. the following test case works as expected:

    { PulseCount.ar(GaussTrig.ar(3, 0.3)) }.plot(2.0);
    { PulseCount.kr(GaussTrig.kr(3, 0.3)) }.plot(2.0);

**Comment by telephon** [comment]
ah of course, yes.

**Comment by telephon** [comment]
`{ LFPulse.kr(1000) }.plot`

**Comment by snappizz** [comment]
Will continue to search for the bug mike saw...
