### ISSUE TITLE
All UGens should calculate 1 sample of output at Ctor

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/sc3-plugins#121]
See the discussion at https://github.com/supercollider/supercollider/issues/2333

**Comment by joshpar** [comment]
Pretty sure this would mean Impulse.ar(0)'s 1 sample of output would be lost if this is done in a blanket fashion. That can't be the only example of this creating such a problem.

**Comment by vivid-synth** [comment]
@joshpar right, we may want to initialize some to "y(-1)" instead of "y(0)" but we should initialize them to something (otherwise we can get garbage memory causing e.g. Nathan's loud accidental shotgun sounds)

**Comment by vivid-synth** [comment]
Whoops, this is a dupe of https://github.com/supercollider/sc3-plugins/issues/115 !

**Comment by joshpar** [comment]
Of course. We just want to make sure we don't apply a blanket solution to this problem. Init SOMETHING - yes, init with first sample of output always? probably not. Thanks!

**Comment by jamshark70** [comment]
> Init SOMETHING - yes, init with first sample of output always? probably not.

But, as noted in the issue I logged about Impulse -> Select -> Lag: If UGens can decide willy-nilly to initialize as y(0) or y(-1), then downstream UGens have no idea how to interpret the incoming initial value in their own Ctors... and chaos ensues. Chaos *already* ensues from this.

IMO it's more dangerous than it might seem at first to allow UGen developers to interpret this part of the API according to whatever whim they're feeling on a given day. The justification is that you need an initial 0 for triggers. But, who decides whether it's a trigger? The trigger source UGen, or the input receiving the trigger? I argue the former doesn't make any sense at all, while the latter would solve a bunch of problems.

**Comment by joshpar** [comment]
And since all signals can be triggers - sigh
