### ISSUE TITLE
Greyhole and JPverb RTAlloc safety

### ISSUE THREAD

**Issue by snappizz** [supercollider/sc3-plugins#133]
A few people have experienced crashes with these two UGens. The help files correctly suggest increasing the server real-time memory size to 2^18 kb (around 260 mb), which fixes the problem.

The server crash is entirely preventable, by adding a check to see if RTAlloc returned NULL and gracefully exiting. However, both these UGens are generated by FAUST, so this is really an upstream issue.

**Comment by vivid-synth** [comment]
To the Faust castle!

**Comment by snappizz** [comment]
Alright, looks like this has been fixed upstream. The remaining steps are to recompile the FAUST code and ensure that nothing has changed in the process. (There may have been a behavior change in FAUST since the last time these two ugens were compiled.)

**Comment by muellmusik** [comment]
File an issue with Faust. The generated code should follow best practice.

**Comment by LFSaw** [comment]
I fixed the `dsp` files, need some help for the compilation (see #142 )

**Comment by LFSaw** [comment]
I don't know where to address this, the plugins compile fine but the server crashes immediately while booting. I assume this is due to an increased amount of memory allocated (?) since smaller FAUST plugins such as

```
import("stdfaust.lib");

process = _,_;
```

 compile and run just fine.

Help much appreciated.

**Comment by LFSaw** [comment]
for the moment, I put the complete (and compiling in faust and faustlive) dsp files here: https://gist.github.com/LFSaw/17a6125b113cd420eaed104a10653b20

**Comment by LFSaw** [comment]
(According to "the FAUST castle" ((c) @vivid-synth), the fix for FAUST RTAlloc safety is covered with https://github.com/grame-cncm/faust/issues/12.

**Comment by LFSaw** [comment]
please review

**Comment by jbtwh** [comment]
Greyhole and JPverb are crashing scsynth for me using basic examples from doc. 
sc version 3.8.0 windows 7

**Comment by snappizz** [comment]
@jbtwh this has been fixed in 3.9. the workaround for 3.8 is to set this in the server options before booting:

    s.options.memSize_(2**18)

the units are kilobytes, so this is around 260MB.

**Comment by totalgee** [comment]
I know this is closed/solved for the future, and indeed I've confirmed it does work in 3.9-beta1, but just FYI unfortunately the "workaround" does **not** work with JPverb in the released v3.8.0 Windows (VS 64-bit version); even setting the `memSize` to 512MB didn't work.  I think the workaround only works with the 32-bit version.

**Comment by LFSaw** [comment]
please open a new issue for this.
