### ISSUE TITLE
soundfont support

### ISSUE THREAD

**Issue by Wang-Yue** [supercollider/sc3-plugins#144]
It would be great if supercollider could support soundfont (sf2) format.  A potential solution is to use fluidsynth library, which could extract samples for a given note/instrument in a sf2 file.

**Comment by LFSaw** [comment]
go ahead!

**Comment by Wang-Yue** [comment]
I have no experience in writing ugen. It's my day 1 using supercollider.  I did try this evening but have trouble with 
1. getting all the parameter needed. UGen seems to only support getting floating point arguments. But how to provide other infos such as sf file path, bank id, etc. 
2. don't know where to put fluid_synth_noteoff() in UGen definition.  
so I stopped trying.

Right now I could only open a fluidsynth session along with supercollider, which is super inconvenient. It also lose the ability to do signal processing for the midi sound it outputs. 

I did contribute to other open source project, such as the cmus player or AsyncDisplayKit library, but supercollider is just too foreign to me. sorry. I hope some pros could help.

**Comment by Wang-Yue** [comment]
copying the samples would be the simple. fluid synth does provide fluid_synth_write_float function, which could be used directly.

**Comment by LFSaw** [comment]
maybe have a look at the way how ladspa plugins are loaded...

https://github.com/supercollider/sc3-plugins/tree/master/source/LadspaUGen

sorry, cannot really help you here :/

	Till

**Comment by jamshark70** [comment]
We should not try to do all of this in a UGen.

Sample management should use buffers. That will be language side code, *not* server.

Crossfade looping might need a UGen different from PlayBuf (we might already have one...?) but it will not be responsible for loading a soundfont.

If I were doing the equivalent of Kontakt's Direct From Disk, I think it would need interaction between language and server, to start the "head" in one buffer while cueing the soundfile, and then handing off at the right time. It wouldn't be easy but trying to hack UGens to manage paths and multiple buffers is crazy, quite contrary to SC's architecture.

**Comment by Wang-Yue** [comment]
Is there some way to create a language binding for a library for sclang? 
There's no difficulty to synth the soundfont/sfz to wav buffers in run time. Libraries such as FluidSynth and https://github.com/WhiteNoise/OpenSFZ do that well. 
The difficult part is to feed the buffer. I just don't know how to make these pieces work together.

**Comment by snappizz** [comment]
@Wang-Yue I see you've already found my sclang SFZ implementation. I welcome contributions and I might be able to attend to some feature requests.

> Right now I could only open a fluidsynth session along with supercollider, which is super inconvenient. It also lose the ability to do signal processing for the midi sound it outputs.

There should be a way to route fluidsynth to SC -- what's your OS? Also, you can make things less inconvenient by launching fluidsynth programmatically as a subprocess of sclang, using String:unixCmd.

**Comment by Wang-Yue** [comment]
@snappizz 

> There should be a way to route fluidsynth to SC -- what's your OS? Also, you can make things less inconvenient by launching fluidsynth programmatically as a subprocess of sclang, using String:unixCmd.

I took some time to set it up. On macOS the thing is not straightforward.  Sending to MIDIEndPoint("FluidSynth virtual port (10000)", "FluidSynth virtual port (10000)" doesn't seems to work. An app called Midi Patchbay is needed to reroute. 

A drawback of this method is I have to use system mixer to mix the sound from SC and FluidSynth together. And I can't manipulate the sound in SC. 

Your sclang SFZ looks great. If it can support the opcode set of VSCO2 Community Edition or Virtual Playing Orchestra it would be ideal.

**Comment by lvm** [comment]
Hello there,
Wrote this Class that creates a `Pipe` to talk to `fluidsynth` (which should be installed in your system): 
https://github.com/lvm/FluidSynth.sc
It's far from complete but it's simple enough to read / adapt. Haven't tested on macOS since I don't have a mac but works pretty well on Linux.

About re-routing fluidsynth to SC, i've been using jackd (plus `SoundIn` [0]) to do that (I believe you could achieve the same with [Soundflower](https://github.com/mattingalls/Soundflower))

[0] https://github.com/lvm/BALC/blob/master/SuperDirt/synths.scd#L342

**Comment by brianlheim** [comment]
Closing as out of scope.

**Comment by sonoro1234** [comment]
> Crossfade looping might need a UGen different from PlayBuf (we might already have one...?) but it will not be responsible for loading a soundfont.

Just found LoopBuf UGen (In sc3-plugins) Best suited for looping than PlayBuf
