### ISSUE TITLE
StkInst_supernova.so: Undefined symbol "_ZN3stk3Stk13showWarnings_E"'

### ISSUE THREAD

**Issue by yurivict** [supercollider/sc3-plugins#159]
Getting this error on FreeBSD:
```
*** ERROR: dlopen '/usr/local/lib/SuperCollider/plugins/StkInst_supernova.so' err '/usr/local/lib/SuperCollider/plugins/StkInst_supernova.so: Undefined symbol "_ZN3stk3Stk13showWarnings_E"'
```

while running the first program from this page: https://github.com/supercollider/supercollider/wiki/Recording-in-SuperCollider-(WIP) in ```sclang```.

**Comment by snappizz** [comment]
i assume you're using the latest dev version of sc. are you also using the latest git version of sc3-plugins?

is the server booted before you run `s.record`?

**Comment by yurivict** [comment]
sc. is 3.8.0, and sc3-plugins is the latest dev. version.
You need to supply all required libs to the shared library build. There is the standard bug that it doesn't fail when libraries are missing.

This linking flag ```-Wl,-z,defs``` prevents this from happening.

**Comment by yurivict** [comment]
With ```-Wl,-z,defs```, the link fails:

```
FAILED: source/StkInst/StkInst_supernova.so 
: && /usr/bin/c++ -fPIC -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -msse -msse2 -mfpmath=sse -std=c++11 -stdlib=libc++ -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -Wl,-z,defs -fstack-protector -shared  -o source/StkInst/StkInst_supernova.so source/StkInst/CMakeFiles/StkInst_supernova.dir/StkInst.cpp.o   && :
source/StkInst/CMakeFiles/StkInst_supernova.dir/StkInst.cpp.o: In function `voiceByNumber(int, stk::Instrmnt**)':
source/StkInst/StkInst.cpp:(.text+0x2ba): undefined reference to `stk::Clarinet::Clarinet(double)'
source/StkInst/StkInst.cpp:(.text+0x2ea): undefined reference to `stk::BlowHole::BlowHole(double)'
source/StkInst/StkInst.cpp:(.text+0x307): undefined reference to `stk::Saxofony::Saxofony(double)'
source/StkInst/StkInst.cpp:(.text+0x324): undefined reference to `stk::Flute::Flute(double)'
source/StkInst/StkInst.cpp:(.text+0x341): undefined reference to `stk::Brass::Brass(double)'
source/StkInst/StkInst.cpp:(.text+0x356): undefined reference to `stk::BlowBotl::BlowBotl()'
source/StkInst/StkInst.cpp:(.text+0x373): undefined reference to `stk::Bowed::Bowed(double)'
```

**Comment by yurivict** [comment]
Since you build a lot of dynamic libraries, the right course of action seems to be:
* Add ```-Wl,-z,defs``` to all link lines.
* Fix all link errors that result from step 1.

**Comment by LFSaw** [comment]
> You need to supply all required libs to the shared library build. There is the standard bug that it doesn't fail when libraries are missing.

> This link flag -Wl,-z,defs prevents this from happening.

@yurivict , since you seem to know a lot (more) than all commenting people here, would you mind filing a PR to fix the linker?
