### ISSUE TITLE
exception in GraphDef_Recv: UGen 'Tartini' not installed.

### ISSUE THREAD

**Issue by jonathancoon** [supercollider/sc3-plugins#163]
None of the sc3-plugins are working. Getting an exception that they aren't installed, even though SuperCollider compiles both /Library/Application Support/SuperCollider/Extensions and ~/Library/Application Support/SuperCollider/Extensions. I have tried placing the sc3-plugins folder in each of those folders (not at the same time, as that causes a conflict error). I have tried using the plugins with SuperCollider 3.7.2, 3.8.0, and 3.9dev with no luck. I am running macOS Sierra 10.12.6.

**Comment by brianlheim** [comment]
Hey @jonathancoon,

Thanks for the report. Can you give us some more details? This would be really helpful to diagnose the problem:
- where did you get the version of sc3-plugins that you're using?
- what is the full output from scsynth during server boot & at the time of failure? If you could paste the actual error message that would be useful not just for diagnosis but also for anyone else who runs across this problem in the future.
- when you say "sc3-plugins folder", does that include the .scx files as well as .sc?

**Comment by jonathancoon** [comment]
- I downloaded the plugins with "git clone --recursive https://github.com/supercollider/sc3-plugins.git"

- Here is the full output during boot up, server boot, and when trying to run Tartini. I also get the same error when I boot the server with an audio interface plugged in.

init_OSC
empty
compiling class library...
initPassOne started
	NumPrimitives = 710
initPassOne done
	compiling dir: '/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Library/Application Support/SuperCollider/Extensions'
	pass 1 done
	numentries = 1169841 / 16660292 = 0.07
	5333 method selectors, 3124 classes
	method table size 17926992 bytes, big table size 133282336
	Number of Symbols 13620
	Byte Code Size 388239
	compiled 440 files in 2.04 seconds
compile done
Class tree inited in 0.01 seconds
Cleaning up temp synthdefs...


*** Welcome to SuperCollider 3.7.2. *** For help press Cmd-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1795 documents in 2.55 seconds
booting 57110
Number of Devices: 2
   0 : "Built-in Microph"
   1 : "Built-in Output"

"Built-in Microph" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 44100.000000, driver's block size = 512
SuperCollider 3 server ready.
Receiving notification messages from server localhost
Shared memory server interface initialized
-> Synth('temp__0' : 1000)
exception in GraphDef_Recv: UGen 'Tartini' not installed.
*** ERROR: SynthDef temp__0 not found
FAILURE IN SERVER /s_new SynthDef not found

- The sc3-plugins folder I'm referring to is the folder with everything in it downloaded using git. I see .sc files in the subfolders, but not .scx

**Comment by jonathancoon** [comment]
Thank you so much! Having downloaded from the releases page, it works great.

**Comment by brianlheim** [comment]
Glad to help!
