### ISSUE TITLE
README for compiled plugins

### ISSUE THREAD

**Issue by celesteh** [supercollider/sc3-plugins#166]
Hello,

The compiled plugins for apple does not include any kind of documentation. A simple README file with installation instructions would be a welcome addition to that release.  The current instructions are hard to locate from the release page and are part of a LOT of text about compiling and other issues, which is somewhat difficult for new users.

(Ideally, plugins could be integrated into the quarks system somehow, but I'm aware this is not going to happen soon.)

**Comment by LFSaw** [comment]
hey, just set up an initial documentaiton and we'll get it in!

**Comment by brianlheim** [comment]
#168
