### ISSUE TITLE
Build failure with VS 2013

### ISSUE THREAD

**Issue by brianlheim** [supercollider/sc3-plugins#167]
Currently, JPVerb fails to build in VS 2013 with the following error:

```
"C:\Users\blh33\supercollider\sc3-plugins\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\blh33\supercollider\sc3-plugins\build\source\JPverb.vcxproj" (default target) (32) ->
(ClCompile target) ->
  C:\Users\blh33\supercollider\sc3-plugins\source\DEINDUGens\JPverbRaw.cpp(586): fatal error C1061: compiler limit : bl
ocks nested too deeply [C:\Users\blh33\supercollider\sc3-plugins\build\source\JPverb.vcxproj]
```

**Comment by brianlheim** [comment]
I am going to report this upstream.

The problem is actually not deep nesting, but just the presence of so many loops in one function. It is a bug with MSVC with a known workaround, so I'm going to report it upstream.

https://support.microsoft.com/en-us/help/315481/bug-too-many-unnested-loops-incorrectly-causes-a-c1061-compiler-error

**Comment by brianlheim** [comment]
Relevant code is here: https://github.com/supercollider/sc3-plugins/blob/master/source/DEINDUGens/JPverbRaw.cpp#L460-L620

**Comment by LFSaw** [comment]
Only seeing this now, thanks for upstreaming!

**Comment by brianlheim** [comment]
We are now building with 2017
