### ISSUE TITLE
v3.9 32-bit Windows release doesn't appear to work on Windows 7

### ISSUE THREAD

**Issue by samaaron** [supercollider/sc3-plugins#178]
For some reason, the v3.9 release doesn't work correctly on Windows 7 (whereas scsynth itself does appear to work just fine on Windows 7).

Looking at the scsynth output, it's saying that the sc3-plugin ugens don't exist - but they're clearly there (and work just fine on Windows 8 and 10).

Perhaps it's just a matter of compiling them in a manner which is compatible with Windows 7?

**Comment by brianlheim** [comment]
Thanks for reporting @samaaron. Not sure if I can address this anytime soon. I don't have a Windows 7 VM to work on. I compiled the release with VS 2017 but I don't know why there would be any compatibility issues there. I could try again with VS 2013 but that would take extra effort thanks to the folks at the Faust project.

**Comment by shimpe** [comment]
To the best of my knowledge visual studio allows for selecting some target platform. Maybe it's set to a too recent version?

**Comment by samaaron** [comment]
Let me dig into this further - I'm getting reports that for a user, it's not working out on Win 10 either - which definitely doesn't match my observations locally. I'll get back to you with further information.

**Comment by brianlheim** [comment]
> To the best of my knowledge visual studio allows for selecting some target platform. Maybe it's set to a too recent version?

Ah, I noticed that we're not setting `WINVER` or one of the other versioning macros for this project (we do it for SC proper). @samaaron I just sent you an experimental build with that set, that's my best guess for a solution at the moment.

**Comment by samaaron** [comment]
I tried it but it sadly made no difference :(

**Comment by brianlheim** [comment]
All right. Sorry, but I can't assist without more info. Is it only sc3-plugins that can't be loaded or plugins in general? And is it some specific library or every one of them? And, does it happen with a normal scsynth install or only with the sonic pi distribution?

I noticed in the report on your repo that the path being passed to LoadLibrary has forward slashes in it. Perhaps Win 7 is more restrictive about that and needs backslashes. I think I need more information before I put time into another fix attempt, though.

**Comment by samaaron** [comment]
It appears to only be sc3 plugins on some systems. I can't get them working on my Win 7 VM at all, but the same Sonic Pi msi works on Win 8 and Win 10.

Sonic Pi doesn't do anything special other than boot Supercollider as you can see in the log files. I'll look into the backslash issue to see if that makes any difference. We're using a strict subset of SuperCollider (scsynth + sc3-plugins).

What's odd is that in some cases SuperCollider starts but just doesn't make any sound when you use synths that include the sc3-plugins and in other cases  (https://github.com/samaaron/sonic-pi/issues/1807) SuperCollider refuses to boot at all.

My assumption is that the standard SuperCollider user base is predominantly macOS and Linux, but Sonic Pi has a large Windows user base due to its use in education - so I expect more of the Windows issues to be observed through our user base :-)

I'll now do two things:

* Check to see if I get a similar error with vanilla SuperCollider
* Check the slash orientation in paths

Do let me know if you'd like me to look into anything else.

**Comment by samaaron** [comment]
Minor update:

Running `scsynth.exe` via the (frankly hideous) `cmd.exe` shell with standard windows `\` separators returns the same errors - but also pops up a large number of warning windows complaining about missing dll files:

* `VCRUNTIME140.dll`
* `MSVCP140.dll`

Hopefully it's just a case of adding these to the msi. It's quite likely that some users have these dlls available system wide and others don't which would explain why we se it working on some systems and not others. Will report back soon...

**Comment by brianlheim** [comment]
> Check the slash orientation in paths

This might need to be addressed at the source level; I just want to rule out other obvious possibilities first. If this is indeed the problem then we ought to be handling that on our end, it's a simple fix.

> My assumption is that the standard SuperCollider user base is predominantly macOS and Linux

Actually, we get most of our downloads from Mac and Windows! We don't seem to get as much reporting from Windows folks though.

**Comment by samaaron** [comment]
> Actually, we get most of our downloads from Mac and Windows! 

Oh, nice to know! I was just assuming not much Windows activity because I hadn't seen it in the wild.

**Comment by samaaron** [comment]
> Check to see if I get a similar error with vanilla SuperCollider

Just to confirm, I get exactly the same missing dll errors with vanilla SuperCollider on Windows 7 using `cmd.exe` and correct `\` separators.

**Comment by brianlheim** [comment]
> Just to confirm, I get exactly the same missing dll errors with vanilla SuperCollider on Windows 7 using cmd.exe and correct \ separators

"Exactly the same" as in the error message still uses forward slashes when it names the path? Also, the scx file is definitely at that path? I have been assuming this but I don't think it's been explicitly stated.

**Comment by samaaron** [comment]
<img width="673" alt="screen shot 2018-01-25 at 16 43 25" src="https://user-images.githubusercontent.com/369/35400521-e5c6c482-01ee-11e8-980e-cbd6fcd59f09.png">

The error messages have backslashes, but other than that they're identical. They wouldn't appear if the path was incorrect, as `scsynth.exe` wouldn't find any `.scx` files and therefore have nothing to complain about :-)

I'm working on adding the missing dll files to see if that fixes things...

**Comment by brianlheim** [comment]
Ok, thank you for testing! I think this is a pretty strong indication that the next thing to try is compiling with VS 2013. AFAICT that ideally shouldn't make a difference, but I'm not a total guru yet when it comes to binary compatibility issues like this.

**Comment by shimpe** [comment]
The missing .dlls may indicate that you need to install the visual studio c++ redistributable from microsoft:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable?forum=vssetup

**Comment by brianlheim** [comment]
Sorry, what are you referencing when you say "the missing dlls"?

**Comment by shimpe** [comment]
@brianlheim  see the minor update from @samaaron about 5 hours ago: 


> "
> but also pops up a large number of warning windows complaining about missing dll files:
> 
> VCRUNTIME140.dll
> MSVCP140.dll
> "

**Comment by brianlheim** [comment]
ahh, I missed that before, I think it was posted while I was replying. Thanks!

**Comment by brianlheim** [comment]
This was fixed; we don't bundle the MSVC runtimes with our binaries so they are missing when sc3-plugins is compiled with a different VS than scsynth.
