### ISSUE TITLE
external libraries not included in release!

### ISSUE THREAD

**Issue by dvzrv** [supercollider/sc3-plugins#184]
Hey there,

I'd like to move sc3-plugins to Arch Linux' [community] repository. However, I'm unable to do that, as the external libraries in the release tarball are missing and I can't build the plugins!
Please re-release the tarball.

Without version tags, it is impossible for me to ship sc3-plugins' dependencies either (good packaging style disallows this).

**Comment by patrickdupuis** [comment]
@snappizz Can we fix this before releasing sc3plugins 3.9.1?

**Comment by dvzrv** [comment]
@snappizz additionally: I guess the versioning of sc3-plugins will always stay in sync with that of supercollider, right?
This way I can create a more strict build script for it.

**Comment by brianlheim** [comment]
We just need to add a release asset like the Supercollider releases have that contains the full code including submodules. We don't have any control over the tarballs GitHub adds automatically

**Comment by brianlheim** [comment]
So, it's not really something that has to be "fixed" anywhere in the codebase, just need to make sure those are up

**Comment by dvzrv** [comment]
@brianlheim I see.
However, in the current state the releases are not very useful, as the external libraries are also not git submodules anymore, so one would have to add them in there (during packaging).
That though, is also not possible because they are unversioned upstream.
I'd be happy to have some up-to-date assets for 3.9.1 to ship with current supercollider.

**Comment by brianlheim** [comment]
> However, in the current state the releases are not very useful, as the external libraries are also not git submodules anymore, so one would have to add them in there (during packaging).

Not sure I understand. If the release assets had the full source tree including the sources from submodules in external_libraries, would that be acceptable for your use case?

**Comment by dvzrv** [comment]
> If the release assets had the full source tree including the sources from submodules in external_libraries, would that be acceptable for your use case?

Submodules would at least give the possibility to get the external libraries in their required version. A better option is of course to include the external libraries (in their required version) in the assets.

Otherwise, if possibly, building with system-wide libraries could also be an option (on Arch [stk is available in version 4.5.1](https://www.archlinux.org/packages/community/x86_64/stk/)). However, [nova-simd](https://github.com/timblechmann/nova-simd/tree/314068939cd52cb44cd7d46c1db309a777fd8686) has not been packaged yet. I don't know how straight forward such a build would be (regarding modifications of source code and the required version vs. using the current stable version).

**Comment by dvzrv** [comment]
@snappizz What would be your suggestion regarding this?

**Comment by snappizz** [comment]
sorry for the late response, i have not been able to dedicate much time to github discussions lately... we have a [packaging script](https://github.com/supercollider/supercollider/blob/develop/package/package) in the core repo that assembles a tarball with all the submodules in it. we can simply write a simplified version of this script for sc3-plugins, use that to create a tarball, and upload that to the release page.

**Comment by dvzrv** [comment]
Hehe, I know how it is. I'm pretty flooded with packaging myself lately.
However, I could give the package script a go and provide it in a pull request. Might take me a couple of days though.

**Comment by gusano** [comment]
@dvzrv I'm an arch package-system noob but wouldn't adding `git submodule init && git submodule update` be an option in your package script?

**Comment by gusano** [comment]
@dvzrv https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git_Submodules

**Comment by dvzrv** [comment]
@gusano Indeed, I could use git, but that's not really clean packaging. I want to provide sc3-plugins in [community] as a non-VCS package.
In any case: The libraries should be provided in a release tarball, so I think a packaging script would be the proper way to go here (helps not just my packaging :) )

**Comment by gusano** [comment]
@dvzrv got it, so you want a package which uses version tags but not version control system? :jack_o_lantern:

**Comment by dvzrv** [comment]
Yeah :)

**Comment by dvzrv** [comment]
ehm.... ping?

**Comment by vivid-synth** [comment]
Ran into (what I believe is) this issue with a new user the other day at a Tidal workshop. On building sc3-plugins it errored on not having the ```nova-simd``` (and possibly other) submodule(s).

If I can help fix this without Arch I'm happy to help.

**Comment by dvzrv** [comment]
@vivid-synth well, #186 might already fix this, but I'm waiting on someone to review and merge it, so i can go on with packaging on Arch.

**Comment by simonvanderveldt** [comment]
Is there a maintainer around that can look at/merge @dvzrv's PR?

I also noticed the current [3.9.1 release](https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.9.1) uses the git hash for the self-uploaded artifact, which is different from the older releases which uses the version. Can this be fixed/reverted to use the version again? That's a lot easier to package since then there's no need to make a specific change to the package for every release.
