### ISSUE TITLE
building supernova plugins: is supercollider source really required?

### ISSUE THREAD

**Issue by dvzrv** [supercollider/sc3-plugins#185]
In CmakeLists.txt [supernova is searched for in a path, that assumes the SuperCollider sources are around](https://github.com/supercollider/sc3-plugins/blob/master/CMakeLists.txt#L15).
However, it seems that they are not really required to build the supernova plugins (it is only required to have an installed version of supercollider with supernova around): I removed the if statement as a test and it compiles (also the supernova plugins).

Am I just doing something completely stupid, or is the supernova search path assuming wrongly?

**Comment by brianlheim** [comment]
This is a good catch. That check should be changed to NOVA_DISK_IO. NovaDiskIO is the only subproject that includes a nova-tt header, and it is off by default.

**Comment by mkrawczuk** [comment]
So this might be why I cannot compile sc3-plugins. I did everything by the instruction, and when running cmake .. in the build directory, an error occurs:
CMake Error at CMakeLists.txt:17 (message):
  The nova-tt submodule in the SuperCollider repository is missing (required
  for SuperNova plugins).  This probably means you forgot to clone
  submodules.  To fix this, run `git submodule update --init` from the root
  folder of the SuperCollider repository

Googled around and found someone else having a similar problem:
https://aur.archlinux.org/packages/supercollider-with-plugins/ 
(see comment by rcrath on 2018-02-12)

**Comment by brianlheim** [comment]
@mkrawczuk - this is where that error message is coming from, yes. What is the full configuration you use to build?
