### ISSUE TITLE
Arch Linux: exception in GraphDef_Recv

### ISSUE THREAD

**Issue by Arseniusz** [supercollider/sc3-plugins#187]
Trying to build and install sc3-plugins.

All plugins are builded and installed without errors or even warnings.
When I try to use any of plugin I got an error (DFM1 for.ex):

_exception in GraphDef_Recv: UGen 'DFM1' not installed._

But plugins docs installed and autocomplete in scide works also.
Both SC and SC3-Plugins are version 3.9

UPD:

I copied TJUgens.so from build directory to TJUgens plugins folder and now DFM1 works.

So it looks like all .so files are not copied properly.
Where should I put it if I want to do it manualy?

**Comment by dvzrv** [comment]
Should be long fixed since sc3-plugins 3.9.1.
I can't reproduce this problem after packaging. If you still experience problems, please reopen!

**Comment by Arseniusz** [comment]
Ok.
