### ISSUE TITLE
Allow partial building of HOAUGens

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/sc3-plugins#197]
Currently, the HOAUGens are not compileable on Windows or on small Embedded Linux systems like Rpi. The reason for this is that some files in the HOAUGens collection have very deep bracket nesting which makes the compiler fail. The number of these files is very small, and they are mostly related to 3-5 order ambisonics binaural decoding. 

It's a bit unfair to exclude users on some platforms simply because of a few files. We should find a way to conditionally build parts of the HOAUGens based on the platform.

**Comment by sonoro1234** [comment]
They build with mingw-w64.
I know it is not supported by supercollider, but please dont use #if __WIN32 but instead #if MSVC which allows mingw to skip msvc restrictions.
