### ISSUE TITLE
cmake asks for nova-tt, but external_libraries/ only has the nova-simd module link

### ISSUE THREAD

**Issue by yurivict** [supercollider/sc3-plugins#199]
See these lines in CMakeLists.txt: https://github.com/supercollider/sc3-plugins/blob/master/CMakeLists.txt#L16 and external_libs: https://github.com/supercollider/sc3-plugins/tree/master/external_libraries

**Comment by brianlheim** [comment]
Those lines are looking for nova-tt in the supercollider repo, not this repo.

**Comment by yurivict** [comment]
There is no supercollider repo during the build of sc3-plugins, there is only the supercolliderpackage installed.
Is supercollider supposed to install ```nova-tt```?

**Comment by simonvanderveldt** [comment]
Could this dependency be made explicit? Depending on transitive dependencies is generally not the best idea.
