### ISSUE TITLE
MdaPiano should round frequency to midi note conversion rather than truncate

### ISSUE THREAD

**Issue by rogerallen** [supercollider/sc3-plugins#25]
There is an issue with the MdaPiano synth that has been reported to the Overtone project.  I think it is an issue for this project to address.  See discussion at https://github.com/overtone/overtone/issues/264

Repeating my comment from there...

The MdaPiano code here
https://github.com/supercollider/sc3-plugins/blob/master/source/MdaUGens/MdaUGens.cpp#L119
takes the freq in and converts it immediately to an integer note with
sc_cpsmidi().  Due to how sc_cpsmidi() is written, we are on the
knife's edge of precision issues as people above have found out.  If
the input frequency is off by any amount towards zero, the integer
note returned is one lower than desired.

In my opinion, MdaPiano should be changed to allow for some slight
errors in the input frequency and use rounding instead of truncation
after calculating sc_cpsmidi().  Simply adding 0.5f prior to converting to an integer would do this.

The sc_cpsmidi and midicps functions are defined in SuperCollider here
and you can see they involve some magic constants:
https://github.com/supercollider/supercollider/blob/master/include/plugin_interface/SC_InlineUnaryOp.h

Here is a test program to show what is happening with any slight error.

```c
/* lets test Supercollider midicps
 *
clang -o cpstest cpstest.cpp
 */

#include <stdio.h>
#include <cmath>
#define float32 float
const double rlog2  = 1./std::log(2.);

inline float32 sc_log2(float32 x)
{
#if __cplusplus >= 201103L
	return std::log2(x);
#elif defined(HAVE_C99)
	return ::log2f(std::abs(x));
#else
	return static_cast<float32>(std::log(std::abs(x)) * (float32)rlog2);
#endif
}

inline float32 sc_midicps(float32 note)
{
	return (float32)440. * std::pow((float32)2., (note - (float32)69.) * (float32)0.083333333333);
}

inline float32 sc_cpsmidi(float32 freq)
{
	return sc_log2(freq * (float32)0.0022727272727) * (float32)12. + (float32)69.;
}

int main(int argc, char **argv) {
    float32 epsilon = 0.0001;
    int t = 64;
    float32 f = sc_midicps((float32)t);
    printf("convert midi to freq...\n");
    printf("%d => %10.6f\n",t,f);
    int t0 = (int)sc_cpsmidi(f-epsilon);
    int t1 = (int)sc_cpsmidi(f);
    int t2 = (int)sc_cpsmidi(f+epsilon);
    printf("add a bit of noise to convert freq back to midi...\n");
    printf("%10.6f => %d\n",f-epsilon,t0);
    printf("%10.6f => %d\n",f,t1);
    printf("%10.6f => %d\n",f+epsilon,t2);
    printf("use rounding instead of truncation\n");
    t0 = (int)(sc_cpsmidi(f-epsilon) + 0.5f);
    t1 = (int)(sc_cpsmidi(f) + 0.5f);
    t2 = (int)(sc_cpsmidi(f+epsilon) + 0.5f);
    printf("%10.6f => %d\n",f-epsilon,t0);
    printf("%10.6f => %d\n",f,t1);
    printf("%10.6f => %d\n",f+epsilon,t2);
}
```

```sh
> clang -o cpstest cpstest.cpp
> ./cpstest 
convert midi to freq...
64 => 329.627563
add a bit of noise to convert freq back to midi...
329.627472 => 63  # OFF
329.627563 => 64
329.627655 => 64
use rounding instead of truncation
329.627472 => 64
329.627563 => 64
329.627655 => 64
```

**Comment by telephon** [comment]
The standard frequency inputs in supercollider are floats and are kept as floats. So this plugin is a special case indeed, and should convert correctly internally.

**Comment by rogerallen** [comment]
Great, thanks!

**Comment by samaaron** [comment]
Yey! :-)
