### ISSUE TITLE
Linux release (3.10.0) has .tar.bz2 extension but is a .tar.gz file

### ISSUE THREAD

**Issue by simonvanderveldt** [supercollider/sc3-plugins#253]
The `sc3-plugins-3.10.0-Source.tar.bz2` file that's part of the https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.10.0 release is a gzipped tar, not a bzip2ed tar.

The commands in the build script are incorrect in that they use `-z` which creates a gzipped tar but name the file `.tar.bz2` https://github.com/supercollider/sc3-plugins/blob/master/package/create_package.sh#L43

The initial script that was added in #186 was correct but #208 changed it to to this incorrect combination.

**Comment by snappizz** [comment]
guh. sorry. luckily we're about to release 3.10.1 anyway.

**Comment by simonvanderveldt** [comment]
Fixed by #254
