### ISSUE TITLE
Cmake option to disable LadspaUGen

### ISSUE THREAD

**Issue by jamshark70** [supercollider/sc3-plugins#259]
LadspaUGen is known to prevent the server from booting in some Linux environments. See #257 (erroneously closed because of a misdiagnosis -- continued at https://github.com/supercollider/supercollider/issues/4421 where it turned out to be an sc3-plugins issue after all).

LadspaUGen hasn't been maintained in several years. See #23 (4.5 years old, unfixed) and #210 (9/2018).

If it isn't going to be fixed (and I have no confidence that it will be), then we should provide a way for users to turn it off.

**Comment by brianlheim** [comment]
This looks related:

https://bugs.launchpad.net/ubuntu/+source/csound/+bug/1754944

https://bugs.launchpad.net/ubuntu/+source/ardour/+bug/1749995

Looks like an upstream problem.
