### ISSUE TITLE
Supernova versions of plugins don't get copied/installed on OS X

### ISSUE THREAD

**Issue by dyfer** [supercollider/sc3-plugins#26]
I'm building SC3-plugins on OSX 10.9 and I've set supernova=ON.

After running "make install" everything builds fine and in my build folder I get "SC3plugins", as well as "source" folders. While the "source" folder does include both regular and supernova plugins, "SC3plugins" (where everything else is) contains only regular ones.

Also, on my system supernova does not find plugins outside its own plugins folder in the SuperCollider.app/Contents/Resources/plugins, is there maybe connection between that and this bug?

**Comment by bagong** [comment]
I cannot confirm that supernova plugins are not copied into the install folder, I get a pair of each at the root of the individual plugins folders. But I can confirm that supernova plugins are only found in very few places on OS X. Next to the one you suggest, they can also be put into userAppSupportDir/Extensions/plugins.
The author of supernova has for the time being decided not to actively support supernova on OS X. But he will review pull requests ;)

**Comment by dyfer** [comment]
I think this has been solved since.
