### ISSUE TITLE
Piano/Klank/Bitcrush classes not defined

### ISSUE THREAD

**Issue by Kebbz** [supercollider/sc3-plugins#267]
Hi, 
I came across a problem with synthdef classes, which are missing „()“ in their definition files and so, they‘re not recognised by Supercollider. Even though I changed it manually, when I‘m booting a server they are changed back to wrong syntax. I‘ve installed SC3 plugins but the problem persists. I would be glad for any help in this matter.
Thanks!

**Comment by brianlheim** [comment]
thanks for the report. can you please give a set of clear steps to reproduce the issue, and any relevant input and/or error messages?

**Comment by Kebbz** [comment]
Hi,
I've just realized that I posted the issue in completely wrong section (I chose the wrong tab of browser...). My problem is not caused neither by SuperCollider nor any of plugins but by FoxDot which I'm using with SC. 
Thank you for your interest in the issue and sorry for confusion.

**Comment by brianlheim** [comment]
no worries! thanks for following up!
