### ISSUE TITLE
how to make an lpc file?

### ISSUE THREAD

**Issue by unculcated** [supercollider/sc3-plugins#268]
There is the fate.lpc file for the lpc examples. How do you make your own?
Thanks

**Comment by joshpar** [comment]
Please see LPCAna.

**Comment by unculcated** [comment]
looked, 
says
his uses the fate.lpc file, created with the following command:

lpanal -p 50 -h 300 fate.aiff fate.lpc

so I go into the sc 
do this
lpanal -p 50 -h 300 /Applications/SuperCollider/SuperCollider.app/Contents/Resources/sounds/a11wlk01.wav /Applications/SuperCollider/SuperCollider.app/Contents/Resources/sounds/a11wlk01.lpc;


get this
-------\
-> nil
ERROR: syntax error, unexpected INTEGER, expecting $end
  in interpreted text
  line 1 char 12:

  lpanal -p 50 -h 300 /Applications/SuperCollider/SuperCollider.app/Contents/Resources/sounds/a11wlk01.wav /Applications/SuperCollider/SuperCollider.app/Contents/Resources/sounds/a11wlk01.lpc; 
            ^^
-----------------------------------
ERROR: Command line parse failed
-> nil

**Comment by joshpar** [comment]
That is using CSound's lpanal. This is another approach that works (and was supported before LPCAna was written). That saves to the same file format that LPCAna uses. You can create it either way.
Please use the sc-users email list for items like this. These aren't underlying code issues but questions about usage. Thanks!

**Comment by unculcated** [comment]
right, LPCAnalyzer helpful doesn't show you how to save to an lpc file format. Im asking on here because I wasn't able to sub to the sc mailing list , and Ive done it a few times. So I know how

**Comment by joshpar** [comment]
LPCAnalyzer is a UGen... LPCAna is a class that creates LPC files for you. Originally they were in sc3-plugins, but I realize now that they are in the JoshMisc quark.

**Comment by unculcated** [comment]
Got it working
