### ISSUE TITLE
Canot install nick collins WT_UGEN

### ISSUE THREAD

**Issue by blibliki** [supercollider/sc3-plugins#270]
Hi there!

I am trying to use Nick Collings Wavelets library but after placing it in the extensions folder and recompile the library and try to run a script I get the following error:

exception in GraphDef_Recv: UGen 'DWT' not installed.

how can I install it? 

thank you!

**Comment by patrickdupuis** [comment]
Please ask for support on the SuperCollider Users mailing list. Nick Collins tends to respond to questions there.

Closing this issue.
