### ISSUE TITLE
MACOSX folder in release zip

### ISSUE THREAD

**Issue by yaxu** [supercollider/sc3-plugins#279]
The release zip https://github.com/supercollider/sc3-plugins/releases/download/Version-3.10.0/sc3-plugins-3.10.0-macOS-signed.zip contains a __MACOSX folder. Therefore if someone unzips the plugins into their extensions folder, things will break. Could this be removed from future releases please?

**Comment by brianlheim** [comment]
@yaxu thanks for the report. can you describe what breaks and how?

**Comment by yaxu** [comment]
This is secondhand via tidal users, i don't use a mac myself.
@LFSaw just said ".. i had to manually remove the __MACOSX folder in my SuperCollider extensions since it was interfering with my manual sc3-extensions install.". I remember someone else also had to do this, but that was a while ago.

Actually it could be that it just creates confusing warnings rather than actually breaking something, I haven't seen it first hand.

**Comment by LFSaw** [comment]
I cannot really be of help here; I just used the install method for `tidal` provided [here](https://github.com/tidalcycles/tidal-bootstrap/blob/master/README.md).

My system was as follows:

+ ProductName:	Mac OS X
+ ProductVersion:	10.14.6
+ BuildVersion:	18G2022
+ SuperCollider 3.10.4
+ self-built sc3-plugins folder
+ some quarks installed

When I download the release zip as mentioned by @yaxu , I do not get a __MACOSX folder though... but I am not deep enough in the material to tell where the problem with the install script lies...

**Comment by yaxu** [comment]
I definitely see a __MACOSX folder in the zip, but this is under linux. I guess MacOS treats it as a hidden folder.

**Comment by LFSaw** [comment]
I stand corrected: the folder is created _next to_ the SC3plugins folder, on inside of it which means that, if unzipped e.g. in the extensions folder, it'll show up there...

```sh
$ unzip -l sc3-plugins-3.10.0-macOS-signed.zip
Archive:  sc3-plugins-3.10.0-macOS-signed.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  08-19-2019 04:42   SC3plugins/
        0  08-19-2019 04:43   SC3plugins/AYUGens/
      343  11-25-2018 15:57   SC3plugins/AYUGens/AYUGens.html
        0  08-19-2019 04:44   __MACOSX/
        0  08-19-2019 04:44   __MACOSX/SC3plugins/
        0  08-19-2019 04:44   __MACOSX/SC3plugins/AYUGens/
      212  11-25-2018 15:57   __MACOSX/SC3plugins/AYUGens/._AYUGens.html
        0  11-25-2018 16:06   SC3plugins/AYUGens/HelpSource/
        0  11-25-2018 16:06   SC3plugins/AYUGens/HelpSource/Classes/
[...]
```

**Comment by brianlheim** [comment]
the `-signed` binaries are from @joshpar , the unsigned binary is from travis CI.

i see these folders as well in the zip. found this: https://superuser.com/questions/104500/what-is-macosx-folder.

i downloaded the 3.10.0 release, ran `zip -d filename.zip __MACOSX/\*`, and reuploaded it, so the issue should be fixed now.

@joshpar can you please document this and make sure to do it for the signed 3.11.0 release?

**Comment by LFSaw** [comment]
thanks, @brianlheim !

**Comment by brianlheim** [comment]
no problem, happy to help

**Comment by yaxu** [comment]
Thanks very much all!
