### ISSUE TITLE
"The nova-simd submodule is missing.": suggested fix (git submodule update) does not work

### ISSUE THREAD

**Issue by jwaldmann** [supercollider/sc3-plugins#285]
I am compiling sc3-plugins (3.10.0) from source (the release tarball). I get
```
cmake -DSC_PATH=../../SuperCollider-3.10.4-Source  -DCMAKE_INSTALL_PREFIX=/opt/supercollider/3.10.4 ..
...
CMake Error at CMakeLists.txt:6 (message):
  The nova-simd submodule is missing.  This probably means you forgot to
  clone submodules.  To fix this, run `git submodule update --init` from the
  root folder of sc3-plugins repository
```
But
```
cd ..
git submodule update --init
fatal: not a git repository (or any parent up to mount point /)
```

**Comment by brianlheim** [comment]
the source tarball is not meant to be used to build this repo; clone it instead.

**Comment by jwaldmann** [comment]
With `git checkout Version-3.10.0` I get
```
[ 11%] Building CXX object source/CMakeFiles/NHHall.dir/NHUGens/NHHall.cpp.o
/home/waldmann/software/music/sc3-plugins/source/NHUGens/NHHall.cpp: In constructor ‘NHHall::NHHall()’:
/home/waldmann/software/music/sc3-plugins/source/NHUGens/NHHall.cpp:56:13: error: ‘printf’ was not declared in this scope
   56 |             printf("Could not allocate real-time memory for NHHall\n");
      |             ^~~~~~
/home/waldmann/software/music/sc3-plugins/source/NHUGens/NHHall.cpp:30:1: note: ‘printf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
```
This may depend on the compiler version (I use gcc-10.0.1 that comes with Fedora-32). When I add `#include <cstdio>`, compilation succeeds.

**Comment by brianlheim** [comment]
fixed in https://github.com/supercollider/sc3-plugins/pull/271; if you are compiling v 3.10 then you might as well compile the tip of master, there's no difference in compatibility and as far as i'm aware the only changes going in between 3.10 and 3.11 have been bug fixes and new ugens.

**Comment by jwaldmann** [comment]
Thanks, will do. I am running into https://github.com/musikinformatik/SuperDirt/issues/192  , perhaps you have an idea?  In any case, thanks for responding!
