### ISSUE TITLE
Check if SSE/denormal compilation is correct for Windows (MSVC)

### ISSUE THREAD

**Issue by totalgee** [supercollider/sc3-plugins#289]
Hi there, after the fix that was made by @jrsurge to fix "CPU spikes" on Windows with SC 3.11.0 (https://github.com/supercollider/supercollider/pull/4504), I'm wondering if anything similar needs to be done for the compilation of SC3-plugins.

There was this fix (https://github.com/supercollider/sc3-plugins/pull/63) done by @sonoro1234 a few years ago to fix denormals, but I wonder if the equivalent changes (related to SSE flags and denormal handling) weren't done for Windows(?). The side effect would be occasional CPU spikes with UGens like JPverb, and generally heavier-than-usual processor usage.

Perhaps all is fine (JPverb is a CPU hog); it would just be great if someone could check. Thanks!

**Comment by totalgee** [comment]
Just an update, the issue may (also or only?) be with the Server monitor (green bar at bottom right of SC-IDE) on Windows…

There, for example, running a single `JPverb` on an i7-6700k desktop in Windows 10 shows ~13% CPU usage (average and peak). However, I just noticed the Task Manager actually shows `scsynth` CPU usage at only 0.7%.  I was comparing this to an old MacBook Air (2012), which showed ~7% CPU usage in the green server bar, which is why I was so surprised by the poor performance on the powerful Windows machine.

On a fairly heavy performance setup, the SC server monitor shows nearly 40-50% CPU usage, but the actual CPU usage according to Task Manager is about 2.5%. I guess SC-IDE is maybe taking the CPU usage and multiplying it by the number of cores on the machine (8, if you include hyper-threading). But even then, it's off by a factor of at least 2.

(So, I'm definitely less worried now, but it would still be good to ensure the SSE flags are correct. ;-)

**Comment by sonoro1234** [comment]
Denormal handling does not depent on compiler flags.  It is done at run time in the main program (scsynth or supernova) and it sufficess for all loaded modules. The place in the main program were it was done was only compiled if SSE was defined but this is corrected now by (supercollider/supercollider#4504)

**Comment by totalgee** [comment]
Thanks @sonoro1234 for confirming!
