### ISSUE TITLE
crash in LadspaUGen.so

### ISSUE THREAD

**Issue by sc3sc3** [supercollider/sc3-plugins#294]
I had a crash with supercollider git master build
and sc3-plugins git master build:

#0  strlen () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00007ffff7dec868 in __GI__dl_exception_create (exception=0x7fffffffcd50, objname=0x2f61707364616c2f <error: Cannot access memory at address 0x2f61707364616c2f>,
    errstring=0x7ffff7df6411 "shared object not open") at dl-exception.c:73
#2  0x00007ffff5eac251 in __GI__dl_signal_error (errcode=0, objname=<optimized out>, occation=<optimized out>, errstring=<optimized out>) at dl-error-skeleton.c:117
#3  0x00007ffff7debae1 in _dl_close (_map=0x555555a15a00) at dl-close.c:839
#4  0x00007ffff5eac2df in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffcd50, operate=0x7ffff79b3070 <dlclose_doit>, args=0x555555a15a00) at dl-error-skeleton.c:196
#5  0x00007ffff5eac36f in __GI__dl_catch_error (objname=0x555555875e20, errstring=0x555555875e28, mallocedp=0x555555875e18, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:215
#6  0x00007ffff79b3735 in _dlerror_run (operate=operate@entry=0x7ffff79b3070 <dlclose_doit>, args=0x555555a15a00) at dlerror.c:162
#7  0x00007ffff79b30b3 in __dlclose (handle=<optimized out>) at dlclose.c:46
#8  0x00007fffd7ccf44b in LADSPADirectoryPluginSearch () from /usr/local/lib/SuperCollider/plugins/LadspaUGen.so
#9  0x00007fffd7ccf53f in LADSPAPluginSearch () from /usr/local/lib/SuperCollider/plugins/LadspaUGen.so
#10 0x00007fffd7ccf1be in load () from /usr/local/lib/SuperCollider/plugins/LadspaUGen.so
#11 0x0000555555575981 in PlugIn_Load (filename=...) at /home/interlichtspielhaus/git/supercollider/server/scsynth/SC_Lib_Cintf.cpp:360
#12 PlugIn_LoadDir (dir=..., reportError=reportError@entry=true) at /home/interlichtspielhaus/git/supercollider/server/scsynth/SC_Lib_Cintf.cpp:393
#13 0x000055555557695c in initialize_library (uGensPluginPath=<optimized out>) at /home/interlichtspielhaus/git/supercollider/server/scsynth/SC_Lib_Cintf.cpp:184
#14 0x000055555559d6d1 in World_New (inOptions=0x7fffffffd350) at /home/interlichtspielhaus/git/supercollider/server/scsynth/SC_World.cpp:299
#15 0x0000555555561d6d in main (argc=13, argv=<optimized out>) at /home/interlichtspielhaus/git/supercollider/server/scsynth/scsynth_main.cpp:320

**Comment by sonoro1234** [comment]
sc3-plugins github search Ladspa:
https://github.com/supercollider/sc3-plugins/issues/210
https://github.com/supercollider/sc3-plugins/issues/288
