### ISSUE TITLE
MedianSeparation causes segmentation fault

### ISSUE THREAD

**Issue by kureta** [supercollider/sc3-plugins#306]
I don't know how to debug or pinpoint the exact cause of the problem but it doesn't always happen and it seems it only happens during the initialization of a Synth. If the Synth is successfully initializes it keeps on working just fine. I am on Arch Linux `5.4.82-rt45-1-rt-lts ` kernel and jack2 v1.9.16-1. Here is a minimal code that results in a segmentation fault:

```
(
SynthDef(\analysis, { |in=0|
	var input, fft, harmonic, percussive;

	input = SoundIn.ar(in);

	fft = FFT(LocalBuf(2048), input);
	# harmonic, percussive = MedianSeparation(fft,FFTTrigger(LocalBuf(2048)),FFTTrigger(LocalBuf(2048)),2048,9);
}).add;

~analyzer = Synth(\analysis);  /segfault occurs on this line
)
```

**Comment by redFrik** [comment]
probably this is because you forgot to wait for the synthdef to be built.  .add is asynchronous - see s.sync below.  hope this helps.

(and these types of questions would be better to discuss first on the mailing list than here in the issue tracker)

```supercollider
(
s.bind{
	SynthDef(\analysis, { |in=0|
		var input, fft, harmonic, percussive;
		
		input = SoundIn.ar(in);
		
		fft = FFT(LocalBuf(2048), input);
		# harmonic, percussive = MedianSeparation(fft,FFTTrigger(LocalBuf(2048)),FFTTrigger(LocalBuf(2048)),2048,9);
	}).add;
	s.sync;  //HERE need to wait for synthdef build before instantiating
	~analyzer = Synth(\analysis);  //segfault occurs on this line
}
)
```

**Comment by kureta** [comment]
You are right. Thank you. I'm closing this issue.
