### ISSUE TITLE
Plugin installation directory on 64bit linux

### ISSUE THREAD

**Issue by gedobbles** [supercollider/sc3-plugins#309]
When trying to install the sc3-plugins version  with the following instructions
```
mkdir build
cd build
cmake -DSC_PATH=../supercollider/ -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release -j15
sudo cmake --build . --config Release --target install
```
I experienced the plugins not to work.
(Message `exception in GraphDef_Load: UGen 'MdaPiano' not installed.`)

I could resolve this by changing
`set(INSTALL_DESTINATION "lib/SuperCollider/plugins")` to `set(INSTALL_DESTINATION "lib64/SuperCollider/plugins")` in `source/CMakeLists.txt:148`.

Therefore I think, there should be a check added for this.

**Comment by tdug** [comment]
https://github.com/supercollider/sc3-plugins/pull/328

I have an open pull request for this currently that is consistent with the implementation in Supercollider's main repo. I'm going to update the README shortly, as suggested.

**Comment by dyfer** [comment]
I believe #328 fixes this - use `LIB_SUFFIX` option when configuring.
