### ISSUE TITLE
Use GHA for CI

### ISSUE THREAD

**Issue by mossheim** [supercollider/sc3-plugins#311]
what @madskjeldgaard has done in https://github.com/supercollider/cookiecutter-supercollider-plugin/pull/29 and the scripts in the main repo are both good references for this.

**Comment by dyfer** [comment]
@brianlheim at some point you indicated interest in implementing this, are you still planning to do that?

**Comment by brianlheim** [comment]
i am interested, but if someone else wants to do it i wouldn't mind. if i do it, i will not have time to start on this for at least a week.

**Comment by dyfer** [comment]
Fixed in #320
