### ISSUE TITLE
ATK: FOA speed of sound

### ISSUE THREAD

**Issue by joslloand** [supercollider/sc3-plugins#317]
ATK issue: https://github.com/ambisonictoolkit/atk-sc3/issues/104

> AtkFoa.speedOfSound = 333.0; // (m/s)
> 
> NOTE: this value is implied by the current setting of the cutoff
> frequency (53 Hz) found in the sc3-plugins code for FoaProximity & FoaNFC
> 
> freq = speedOfSound / 2pi // wavenumber = 1
> speedOfSound = 53 * 2pi // 333.0
> 
> this value is the speed of sound @ 3C
> https://www.weather.gov/epz/wxcalc_speedofsound
> 
> TODO: consider updating sc3-plugins to align with
> AtkHoa.speedOfSound = 343.0

The fix for this is simple. For FoaProximity and FoaNFC, replace the frequency setting of 53.0 Hz with 343.0 / 2pi -> 54.59014548052

There are four lines to be updated:
https://github.com/supercollider/sc3-plugins/blob/fa550fbbe28f78ac1872ed580b21b78ef6b63c42/source/ATK/AtkUGens.cpp#L1949
https://github.com/supercollider/sc3-plugins/blob/fa550fbbe28f78ac1872ed580b21b78ef6b63c42/source/ATK/AtkUGens.cpp#L1999
https://github.com/supercollider/sc3-plugins/blob/fa550fbbe28f78ac1872ed580b21b78ef6b63c42/source/ATK/AtkUGens.cpp#L2063
https://github.com/supercollider/sc3-plugins/blob/fa550fbbe28f78ac1872ed580b21b78ef6b63c42/source/ATK/AtkUGens.cpp#L2113

**Comment by joslloand** [comment]
Don't forget to update the [README](https://github.com/supercollider/sc3-plugins/blob/main/source/ATK/sc/README.md)!

**Comment by joslloand** [comment]
@mossheim, @telephon, @joshpar 

The question is one of etiquette. Is it preferred for me to directly make the above listed changes to the ATK's plugins, or would it be preferable for me to make a PR?

Do let me know, as I'd like to be sure play nicely!

**Comment by dyfer** [comment]
Hi @joslloand 
I think anything that gets into the main branch needs to go through a PR anyway, so making one is probably the best way forward.

**Comment by joslloand** [comment]
Thanks @dyfer, I'll go ahead and prepare a PR.

It would be great to be able to have the update in to coincide with the upcoming SC 3.12 release.

**Comment by dyfer** [comment]
> It would be great to be able to have the update in to coincide with the upcoming SC 3.12 release.

Noted. 
I have a feeling the 3.12 release of sc3-plugins will be a bit behind the SC release, FYI.

**Comment by joslloand** [comment]
@dyfer, yes, I would expect so... but was hoping to be ready for it....
