### ISSUE TITLE
JoshGrainUGens not compiling for 3.7.x versions

### ISSUE THREAD

**Issue by Munzey** [supercollider/sc3-plugins#39]
see this [supercollider mailing list forum issue] (http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/sc3-plugins-broken-compile-for-sc3-5-7-td7599951.html). Checking out the 3.5 tag version of this file solves the issue

**Comment by joshpar** [comment]
tim - I see sc_isfinite is mentioned by you as missing. Was this deprecated / removed? and if so, do you know what replaces it?
Thanks,
Josh

******************************************
/* Joshua D. Parmenter
http://www.realizedsound.net/josh/

“Every composer – at all times and in all cases – gives his own interpretation of how modern society is structured: whether actively or passively, consciously or unconsciously, he makes choices in this regard. He may be conservative or he may subject himself to continual renewal; or he may strive for a revolutionary, historical or social palingenesis." - Luigi Nono
*/

**Comment by danstowell** [comment]
@joshpar it's missing in 3.5.x (as tim said in that linked discussion) but this issue is about 3.7.x, where the function does exist: https://github.com/supercollider/supercollider/blob/master/include/plugin_interface/SC_InlineUnaryOp.h#L75

I don't understand why @Munzey referred to that linked discussion, it doesn't seem to be about 3.7.x

**Comment by Munzey** [comment]
ahh its my bad, I installed supercollider via apt-get.  Will build sc from source. sorry for the trouble

**Comment by timblechmann** [comment]
fwiw, avoid all the trouble and use c++11 and `std::isfinite`: we have 2015 after all and don't need to waste time by working on compatibility layers for legacy compilers anymore, as gcc, clang and msvc are pretty standard-compliant these days
