### ISSUE TITLE
Duplicate classes in faust_src

### ISSUE THREAD

**Issue by ghost** [supercollider/sc3-plugins#43]
SuperCollider 3.6.6 on Mac OSX El Capitan 10.11.1

At first I kept getting this error message (displayed here in full).

As soon as I deleted the 'faust_src' folder and it compiled successfully. Hope this helps someone.

compiling class library...
	NumPrimitives = 688
	compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Users/lightspeed/Library/Application Support/SuperCollider/Extensions'
ERROR: duplicate Class found: 'Greyhole' 
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/faust_src/Greyhole.sc
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/sc/Greyhole.sc

ERROR: duplicate Class found: 'GreyholeRaw' 
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/faust_src/Greyhole.sc
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/sc/Greyhole.sc

ERROR: duplicate Class found: 'JPverb' 
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/faust_src/JPverb.sc
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/sc/JPverb.sc

ERROR: duplicate Class found: 'JPverbRaw' 
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/faust_src/JPverb.sc
/Users/lightspeed/Library/Application Support/SuperCollider/Extensions/sc3-plugins-master/source/DEINDUGens/sc/JPverb.sc

**Comment by telephon** [comment]
Yes, I remember the same here. @LFSaw – do you know a fix?

**Comment by LFSaw** [comment]
how did you install this? for me this doesn't happen (cmake ..; make; make install + including resulting SC3plugins folder via IDE preferences into sclang)

**Comment by rzzr** [comment]
https://github.com/supercollider/sc3-plugins/blob/master/osx_package/README-for-mac-distro.txt
