### ISSUE TITLE
outdated stk sources included with tarball

### ISSUE THREAD

**Issue by hzulla** [supercollider/sc3-plugins#44]
The [stk source copy](https://github.com/supercollider/sc3-plugins/tree/master/source/StkUGens/stk-4.4.2) that comes with the sc3 plugins is outdated. The tarball contains 4.4.2, last [stk release is 4.5.0](https://github.com/thestk/stk/) more than a year ago.

**Comment by danstowell** [comment]
thanks for pointing this out. does it cause a problem?

**Comment by hzulla** [comment]
It's more a janitorial issue, I guess.

I'm currently trying to [package Sonic Pi for Debian/Ubuntu](https://launchpad.net/~hzulla/+archive/ubuntu/sonic-pi), which needs the sc3 plugins, so those got packaged as well.

Debian packaging rules tell packagers to [avoid embedded source code copies](https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles) but use existing Debian packages whenever possible.

Debian comes with stk-4.4.4. I tried to package the sc3 plugins with the Debian library, but they have a [small error](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805549) with their current package. Once that one is resolved, it is indeed possible to build, link and package the sc3 plugins against the Debian library.

The Debian multimedia packagers told me on irc that they may switch to stk-4.5.0 soon, so this issue is just to notify you about it.

**Comment by hzulla** [comment]
stk-4.5.0 changed some filenames, so some `include` lines of the Stk plugin may need to be updated for it.

**Comment by sonoro1234** [comment]
In issues #33 I anounced a new Stk wrapping as the old one is not working.
Nobody has aswered

**Comment by crucialfelix** [comment]
I can understand using the debian stk if this was a debian-only package.

But since sc plugins are crossplatform I think it only causes more
maintenance problems to have compilation different for one platform.
In this case I think included source code is better.

my 2c

**Comment by danstowell** [comment]
@crucialfelix we already handle it for debian in supercollider's main codebase: the debian packaging scripts patch SC to use system boost rather than the bundled one. this happens all in "downstream" and the SC developers never need to know. the same thing would happen here, we don't need to worry about it in our upstream.

@hzulla I'm not sure if you plan to do it the same way, but you should do! Here is [the patch that changes it to build against a system lib](http://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git/tree/debian/patches/system-lockfree.patch) and here is [on line 45 the command that tells debian to strip bundled libraries out of our source code download](http://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git/tree/debian/rules#n45).

If I understand right, @hzulla you can do as I describe, and if the STK API is unchanged then our code doesn't need to change, though we can upgrade our STK (and maybe switch to @sonoro1234 's code too!) whenever we like. That make sense?

**Comment by timblechmann** [comment]
@hzulla if the sc3-plugins depend on a specific versions of stk, which is not available as debian package, it is a good idea to use the bundled version of stk.

@sonoro1234 does your new binding have an API compatibility with the old classes? if they are not a drop-in replacement, the old stk bindings will still have to be kept around for backwards compatibility purposes ... (maybe it makes sense to create a new sc3-plugins repo for those plugins which fail to achieve certain quality standards)

**Comment by hzulla** [comment]
@timblechmann I'm not much of an expert on the sc3 plugins, just a user through Sonic Pi. When I compiled the plugins using stk-4.4.4, they seemed to work fine (but I didn't test thoroughly).

There is an obvious benefit in updating to newer libraries in order to benefit from bug fixes and improvements. Also, the Debian rules are obviously right when they want people to build against existing shared libraries to save memory and reduce the burden of maintaining several versions of the same library on a system.

**Comment by sonoro1234** [comment]
@timblechmann  The api changes a little but it would be the "price" for something to work. 372 lines of new code where easier for me that chasing bugs in 1589 lines. Of course both bindings could be keeped without disturbing each other.

**Comment by petterreinholdtsen** [comment]
@danstowell asked if the old stk version causes a problem.  While working on the Debian packaging, I noticed the old stk version have very old config.guess and config.sub files (from 2004). I know from earlier experience that this causes a problem on some architectures, notably those architectures added the last 10 years, and where support has been added in more recent config.* files.

Btw, perhaps the use of the internal stk library can be made optional in the cmake build rules?  It would make the Debian specific patch smaller.

**Comment by danstowell** [comment]
Hi all - I [proposed a new build flag SYSTEM_STK](https://github.com/supercollider/sc3-plugins/pull/53) - please could you test & review the pull request?

**Comment by hzulla** [comment]
I'd like to propose https://github.com/supercollider/sc3-plugins/pull/56 as an evolutionary step on this and ask for your review. Thanks.

**Comment by telephon** [comment]
I've just merged that one, although I didn't realise that there was a discussion about it here. I hope it's ok.

**Comment by hzulla** [comment]
Thank you. Yes, imho that's OK.
