### ISSUE TITLE
Requesting new release: 3.7.0-alpha1 piano is out of tune, git head is ok.

### ISSUE THREAD

**Issue by hzulla** [supercollider/sc3-plugins#45]
Hi there.

The sc3 plugins are being used by [Sonic Pi](https://github.com/samaaron/sonic-pi/), thanks guys.

```
m = [
  chord(:A3, :minor),
  chord(:F3, :major),
  chord(:C3, :major),
  chord(:G3, :major)
].ring

live_loop :chords do
  c = m.tick
  use_synth :beep
  play_pattern_timed c, 0.125, release: 0.5
  use_synth :piano
  play_pattern_timed c, 0.125, release: 1
  sleep 1-6*0.125
end
```

The current sc3 plugins v3.7.0-alpha1 release contains a piano that is [out of tune](https://groups.google.com/forum/#!topic/sonic-pi/cpizeAxpjjI). Here is an [example audio file](http://www.filedropper.com/sonicpi-with-sc3plugins370alpha1).

When using the current version in git, it's ok, [example audio file](http://www.filedropper.com/sonicpi-with-sc3plugins-git20151018-dfb0f8f).

Since a few people are self-compiling the sc3 plugins for their system, it would be beneficial if you could push a 3.7.0-alpha2 release. Thanks!

**Comment by crucialfelix** [comment]
we are doing 3.7 beta in just a bit. so rather than 3.7.0-alpha2 just go
ahead and do a 3.7 beta

**Comment by hzulla** [comment]
Great, thanks!

**Comment by danstowell** [comment]
@hzulla where is it that you're looking, to find a release? I've forgotten where we put them.

**Comment by hzulla** [comment]
Here: https://github.com/supercollider/sc3-plugins/releases

**Comment by danstowell** [comment]
OK thanks. Ideally this should not be done until:

- [ ] STK 4.4.4 update is merged or rejected (#46)
- [ ] the "new" STK bindings are merged or rejected, or if @sonoro1234 doesn't give us a PR for it (#33)

**Comment by hzulla** [comment]
No problem. I packaged the git head as .deb for now.

**Comment by danstowell** [comment]
Stk stuff is done, ready for beta IMHO

**Comment by petterreinholdtsen** [comment]
A new tagged release would be nice for us packaging the Debian package.

**Comment by danstowell** [comment]
https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.7.0-beta

**Comment by hzulla** [comment]
Cool. Thank you very much!
