### ISSUE TITLE
GVerb glitch

### ISSUE THREAD

**Issue by telephon** [supercollider/sc3-plugins#49]
compare:

```

{GVerb.ar(Dust.ar(5), SinOsc.kr(0.3, 0.5pi).range(10, 14), drylevel:0)}.play

{GVerb.ar(Dust.ar(5), SinOsc.kr(0.3).range(10, 14), drylevel:0)}.play
```

The second has a major glitch, while the first is perfectly smooth.

**Comment by sonoro1234** [comment]
letting compile with that line is even worse as the comment says!!

**Comment by vivid-synth** [comment]
Out of curiosity why is this issue in the sc3-plugins repo instead of the supercollider repo? GVerb is in supercollider/server/plugins/ReverbUGens.cpp

**Comment by snappizz** [comment]
moving to core repository
