### ISSUE TITLE
virtual room plugins (christmas present)

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/sc3-plugins#55]
Hi,

Just published a RIR generator of virtual room (image method of Allen an Berkley) plus late reverb modeling by feedback delay networks in:

https://github.com/sonoro1234/DWGReverb

Only source so must be compiled. Script in Lua should be translated (two plugin definitions and a Synthdef) (I someone translates please fork and commit sc file)

I am quite satisfied with sound quality an efficiency.

Take a look and post your comments.

happy holidays for everyone
victor

**Comment by telephon** [comment]
```  
               ø
              /i\
             /_\_\
            /_/_o\
           /_ø_\_\_\
            /_/_/o\
         /ø\_\_\ø\_\_\
        /_/_/ø/_/_/_/_\
         /_\_\_\_\o\_\
      /_/0/_/_/_0_/_/ø/_\
        /_\_\_\_\_\_\_\_\
  /__/o/__\/_/ø/_/_/o/_/0/_\
            [___]  
              [_] 

```

**Comment by sonoro1234** [comment]
Ha, ha ;-)

I also added an ambisonics version.

**Comment by telephon** [comment]
Now it just needs to be wrapped in christmas paper ;)

**Comment by backseatviolist** [comment]
@sonoro1234 Very cool! I submitted a PR for an sclang translation.
