### ISSUE TITLE
Licensing question: ATK

### ISSUE THREAD

**Issue by hzulla** [supercollider/sc3-plugins#61]
Hi,

packaging sc3-plugins for Debian is chugging along.

Now, we need to clarify all licensing issues, hooray!

There is an unclear section in the [ATK Readme file](https://github.com/supercollider/sc3-plugins/blob/master/source/ATK/sc/README):

> The filter kernels distributed with the Ambisonic Toolkit are licensed under a Creative Commons Attribution-Share Alike 3.0 Unported License and are copyright the Ambisonic Toolkit Community and Joseph Anderson, 2011.

However, I am not sure how to interpret this, since I did not find filter kernels distributed within the sc3-plugins git tree, only code to read and convert soundfield kernel files in [sc/Classes/](https://github.com/supercollider/sc3-plugins/blob/master/source/ATK/sc/Classes/). Is this a copied boilerplate license from the original ATK that doesn't fully apply to the UGen plugin?

Please advise. Thanks.

**Comment by hzulla** [comment]
Paging @joshpar and @joslloand for advice on this. Thanks!

**Comment by miguel-negrao** [comment]
I think the kernels are downloaded separately by the user at the moment, I think. It could be good to include them on a debian packag though.

**Comment by hzulla** [comment]
But that's an ATK packaging issue, not an SC3 plugins issue, I presume.
