### ISSUE TITLE
Licensing question: Re-consider the sc3 plugins license?

### ISSUE THREAD

**Issue by hzulla** [supercollider/sc3-plugins#62]
Hi,

for the Debian package, I have gone through the sc3 plugins tarball and tried to identify all licenses used in it. This is the result:

http://anonscm.debian.org/cgit/pkg-multimedia/supercollider-sc3-plugins.git/tree/debian/copyright

The findings are:

* SuperCollider itself is GPL-3.0+
* the SC3 plugins default license is GPL-2.0+
* some SC3 plugins are GPL-3.0+ in reference to SuperCollider
* most SC3 plugins are GPL-2.0+, possibly in reference to the earlier version of SuperCollider
* some SC3 plugins are LGPL-2.1+
* there are some Boost, BSD and MIT licensed files in there, too.

While none of this is really a problem, I'd humbly suggest to consolidate the licenses to GPL-3.0+ where possible, in accord with SuperCollider itself.

**Comment by danstowell** [comment]
None of this is a problem, and sc3-plugins is deliberately permissive - it would send the wrong message if we coerced this repository into one licence. That's just my opinion, but I'll close this. Reopen it if there are actual problems.

**Comment by hzulla** [comment]
OK, thanks for clarifying.

**Comment by telephon** [comment]
You could add this suggestion to the helpfile of sc (writing plugins)

**Comment by LFSaw** [comment]
just for the records, I am fully supporting @danstowell here.

**Comment by timblechmann** [comment]
ianal, but since iirc the supercollider headers are GPL-2.0+, all plugins using those headers have to use a compatible license when being distributed. plugin *code* can use more permissive licenses, but the binaries will end up being GPL-2.0+
