### ISSUE TITLE
EnvDetect must not accept control rate input! 

### ISSUE THREAD

**Issue by RitheshKumar** [supercollider/sc3-plugins#68]
Please make a provision that giving a control rate signal as an input to the EnvDetect class throws an error. 
```
(
SynthDef("help-EnvDetect",{Out.ar(0,
	
	SinOsc.ar(    [440,440] , 0,  0.3*EnvDetect.ar( LFNoise1.kr(20), MouseX.kr(0.001,0.1,'exponential'),                                                     
		                                                                                       MouseY.kr(0.001,0.1,'exponential')     )       ) ) 
}  ).play
)
```

I did this, and I almost got my ears damaged!!!  
A poll gave me this:

{ Poll.kr( Impulse.kr(10), EnvDetect.ar( Saw.kr(30), 0.1,   0.2  )  ) }.play;

UGen(EnvDetect): 0.000122542
UGen(EnvDetect): 2.48154e+26
UGen(EnvDetect): 3.95078e+26
UGen(EnvDetect): 4.82066e+26
UGen(EnvDetect): 5.3357e+26
UGen(EnvDetect): 5.64063e+26
UGen(EnvDetect): 5.82118e+26
UGen(EnvDetect): 5.92808e+26

**Comment by telephon** [comment]
Thank you for reporting! 

Remember: when using supercollider, do not forget to wear adequate hearing protection!

... well a grain of truth: if you explore unknown territory, maybe it is good not to do that with headphones / full volume.

**Comment by RitheshKumar** [comment]
Honestly,  I was lucky that I was in the lowest volume! :P now, I've learnt a lesson forever! Glad you fixed it.
