### ISSUE TITLE
plugin profiling

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/sc3-plugins#69]
Hi ,

I am trying to do plugin profiling with gprof:

I set cmake -DCMAKE_CXX_FLAGS=-pg -DCMAKE_MODULE_LINKER_FLAGS=-pg to get 
that
but when I try to run scsynth it gets blocked in the plugin loading phase

Something I am missing?

Best
victor bombi

**Comment by sonoro1234** [comment]
seems that gprof  can't profile shared libraries. As they say at mingw64 lists. They don´t provide any alternative. May be you know one?

**Comment by brianlheim** [comment]
This is probably a good question for a mailing list.

**Comment by LFSaw** [comment]
also, the mingw build process is currently unsupported (use VS on windows as https://github.com/supercollider/supercollider/blob/develop/README_WINDOWS.md describes)
