### ISSUE TITLE
Licensing question: DEINDUGens

### ISSUE THREAD

**Issue by hzulla** [supercollider/sc3-plugins#70]
Hi,

the DEINDUGens has a minor licensing issue. The original code is

```
// author: "Julian Parker"
// license: "none"
// copyright: "(c) Julian Parker 2013"
```

yet the faust code generator (?) [added a GPL-2+ license](https://github.com/supercollider/sc3-plugins/blob/master/source/DEINDUGens/JPverbRaw.cpp#L27-L45) to it.

I suspect that this is also what Julian wanted, but just to clarify and to appease the licensing demons at Debian, it would be helpful if the license-entry could be clarified to be GPL-2+.

**Comment by hzulla** [comment]
Maybe someone can contact Julian and ask him?

**Comment by LFSaw** [comment]
@hzulla thanks for looking into this!
I believe this is not for all DEINDUgens the case (some are written by julian some are by myself), they are also not all relying on FAUST.

I guess, the original FAUST definition should keep the original licensing by Julian (I'll ask him to clarify this), whereas the derived version that uses the faust generator needs to comply with GPL-2+. What I however do not understand is, why the copyright for the complete file is attributed to Stefan ( @kaoskorobase ). Doesn't this only apply for the parts he added (via the code generator)?

**Comment by LFSaw** [comment]
In any case, Julian just wrote me that he's fine with GPL:

Julian:
> I think both license blurbs were generated automatically
Never really thought about it tbh
But the intention was that the code was licensed the same way as sc in general right?
If that's gpl, then fine by me

**Comment by LFSaw** [comment]
sorry, forgot to mention the issue in 91f67226b3d1c7a74a9cfc2d91d73a07de187315 (which closes this issue)

**Comment by hzulla** [comment]
No problem and thanks! I have just packaged the new release for Debian and the new package awaits review for inclusion.
