### ISSUE TITLE
OteySoundBoard and OteyPiano crash server

### ISSUE THREAD

**Issue by snappizz** [supercollider/sc3-plugins#76]
Running Ubuntu Studio 14.04, 32-bit. Kernel is 3.16.0-31-lowlatency. Running the most minimal use of OteyPiano causes scsynth to crash with only a message saying `RESULT = 0`.

**Comment by sonoro1234** [comment]
@snappizz  Please tell version of scsynth (scide) and version of sc3-plugins (OteyPiano Changed recently) and the sclang code making it happen.

**Comment by snappizz** [comment]
Using the latest master of both repositories. The following code is enough to cause a crash:

    {OteyPiano.ar*0.1}.play

**Comment by sonoro1234** [comment]
It is not happening here!!

**Comment by snappizz** [comment]
With some printf debugging, the crash doesn't happen until the call to `unit->soundboard.reverb(out[i]);` (OteyPiano.cpp, line 404). I have verified that OteyPianoStrings is working but OteySoundBoard causes the same crash.

**Comment by snappizz** [comment]
Eureka! The problem was the for loop. Changing `int i;` to `int i = 0;` fixes this bug.

**Comment by sonoro1234** [comment]
great catch. Thanks Nathan.

**Comment by snappizz** [comment]
Fixedby #77.
