### ISSUE TITLE
Compiling sc3-plugins in Windows with MSVC 64 bits

### ISSUE THREAD

**Issue by llloret** [supercollider/sc3-plugins#79]
Hi, I know that sc3-plugins are not building at the moment with MSVC, so I thought I would give it a try and see if I can fix that.

I open this issue to track the progress on this.

**Comment by llloret** [comment]
I have tried to compile, and I get a lot of errors like this (one for every plugin):
`D:\sc\sc3-plugins\source\GlitchUGens\GlitchUGens.cpp(678): error C2375: 'load' : redefinition; different linkage`

Now, if I understand correctly, to define a plugin, you need to have a `PluginLoad`, which is there and looks fine. BUT, I can see that the plugins also define the load functions separately (which is what the PluginLoad is doing), so I don't understand that. If I comment the load declaration, then it compiles fine. The separate load declaration looks like this:
`void load(InterfaceTable *inTable);`

From what I can see in the supercollider official plugins in the server director, **they do not declare the load separately**, they only have the PluginLoad, as I would expect. Is there any reason to have the load? Is this something that may requires and `#ifdef _WIN32`, to remove it on Windows only?

**Comment by llloret** [comment]
@bagong, I have made a test with BlitB3 in AntiAliasingOscillators with the change I propose, and it seemed to be ok.

Would you like me to put a Pull Request, and you can test on your side as well?

**This is compiling with MSVC 64 bits, which I think was one of the things that you were trying to do to keep the interest in Windows.**

**Comment by bagong** [comment]
I'll test anything you provide! It might take a day or two, but I am definitely going to support you within the range of my capabilities!

**Comment by llloret** [comment]
Just made a PR #80.

**Comment by bagong** [comment]
Thanks man!!
