### ISSUE TITLE
Pan parameter of TGrains2

### ISSUE THREAD

**Issue by marierm** [supercollider/sc3-plugins#81]
The doc of TGrains2 states that the pan parameter should behave like PanAz, but it is not the case. It behaves rather strangely. 

``` supercollider
b = Buffer.read(Server.default, Platform.resourceDir +/+ "sounds/a11wlk01-44_1.aiff");
x = {TGrains2.ar(
    numChannels: 2,
    trigger: Impulse.kr(10),
    bufnum: b.bufnum,
    rate: 1,
    centerPos: MouseX.kr(0, BufDur.kr(b)),
    pan: MouseX.kr(-1,1.01)
);
}.play;
```

The sound should be panned fully to the left when pan is at -0.5 and fully to the right when pan is at 0.5.  Here, pan behaves more like Pan2, but inverted.  Also, the panning goes abruptly from one side to the other when pan goes above 1.00 or below -1.00.

Compare with this:

``` supercollider
{PanAz.ar(2, SinOsc.ar(mul:0.1), MouseX.kr(-1.01, 1.01))}.play;
```

**Comment by snappizz** [comment]
Here's the pan bit from source code of TGrains2: https://github.com/supercollider/sc3-plugins/blob/master/source/BhobUGens/BhobGrain.cpp#L288.

Compare to PanAz: https://github.com/supercollider/supercollider/blob/master/server/plugins/PanUGens.cpp#L1504

**Comment by snappizz** [comment]
I can't test right now, but TGrains should exhibit the same bug. https://github.com/supercollider/supercollider/blob/f7464ac463b02add1fe490ac3785e8dc222502e7/server/plugins/DelayUGens.cpp#L6203

**Comment by snappizz** [comment]
The intent of the author of the plugin was to follow a convention seen in GrainBuf -- when numChannels is 2, use Pan2, and when numChannels is greater than two, use PanAz. However, two mistakes were made: the intended behavior was not documented, and Pan2 was not correctly implemented (causing the wraparound).

The damage runs deeper than TGrains2. We found that several of the granular ugens in the core SC repository also have inconsistent and incorrectly implemented panning behavior.
