### ISSUE TITLE
BlitB3 can "freeze" at low frequencies

### ISSUE THREAD

**Issue by mhetrick** [supercollider/sc3-plugins#82]
The BlitB3 uGen is freezing on Windows 10 (64-bit) using the pre-compiled plug-in library and SC 3.7.1 (also 64-bit).

I'm using the following line of code:

`{BlitB3.ar(MouseX.kr(0.01, 10000))}.scope`

If I move my mouse to the far left of my screen, the uGen will occasionally stop generating. Sometimes, it will start generating again after a few seconds. I did one test where it took about two minutes to start generating again.

**Comment by snappizz** [comment]
The same problem occurs with the LFNoise ugens, and it's a consequence of the way phase is tracked. The LFDNoise ugens fix the freezing problem, but are slightly less efficient.

This bug isn't too hard to fix, but in a similar vein we could lose efficiency. The best plan of action is to implement "BlitDB3" and experimentally evaluate the efficiency losses. They might be significant enough to warrant a new ugen. If they aren't, we merge BlitDB3 into BlitB3.
