### ISSUE TITLE
JoshUGens doesn't use the new help system

### ISSUE THREAD

**Issue by snappizz** [supercollider/sc3-plugins#89]
Wanted to advertise this in case someone is up for a lot of grunt work :) I might attack this myself.

**Comment by snappizz** [comment]
here's a list. I will try to cross things off as they are converted

- AtsAmp
- AtsFile
- AtsFreq
- AtsNoiSynth
- AtsParInfo
- AtsSynth
- Balance
- BFDecode1
- BFEncode1
- BFEncode2
- BFEncodeSter
- BFManipulate
- BFMixer
- BufGrainB
- BufGrain
- BufGrainI
- delete_me
- DelTapRd
- DelTapWr
- FMGrainB
- FMGrain
- FMGrainI
- FMHDecode1
- FMHEncode1
- FMHEncode2
- LPCAna
- LPCFile
- LPCSynth
- LPCVals
- Maxamp
- Metro
- MonoGrainBF
- MonoGrain
- MoogVCF
- OverlapTexture
- PanX
- Player
- ProcEvents
- ProcMod
- ProcModR
- PVAna
- PV_BinBufRd
- PV_BinDelay
- PV_BinPlayBuf
- PV_BufRd
- PV_EvenBin
- PVFile
- PV_Freeze
- PV_FreqBuffer
- PVInfo
- PV_Invert
- PV_MagBuffer
- PV_MagMap
- PV_MaxMagN
- PV_MinMagN
- PV_NoiseSynthF
- PV_NoiseSynthP
- PV_OddBin
- PV_PartialSynthF
- PV_PartialSynthP
- PV_PlayBuf
- PV_RecordBuf
- PV_SpectralEnhance
- PV_SpectralMap
- PVSynth
- SinGrainBBF
- SinGrainBF
- SinGrainB
- SinGrain
- SinGrainIBF
- SinGrainI
- Tendency
- WarpOverlap
- WarpZ

**Comment by telephon** [comment]
There is another issue here: there are a lot of classes in there that are not plugins but general helper classes and even method extensions. These should be moved to a Quark. (not those that are directly related to the UGens of course).

 I have talked to Josh about it, but I think he hasn't had the time to get it done. Just noting it here.

**Comment by dotinspace** [comment]
Also, `DelTapWr`/`DelTapRd`, aren't they already in the SC class library? If not, wouldn't need other names, lest they would conflict with the help files already present in the base installation?

**Comment by snappizz** [comment]
They must have originally come from JoshUGens and graduated to the core library, but the help files weren't removed.

**Comment by dotinspace** [comment]
Okay, got it. Disregarding those.

**Comment by joshpar** [comment]
Any classes still in JoshUGens rely, at some level, on the UGens in there. Can we make quarks that depend on UGens in sc3-plugins yet, and have it act in a sensible way?


> On Jun 13, 2016, at 1:00 PM, Daniel W. D. <notifications@github.com> wrote:
> 
> Okay, got it. Disregarding those.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/supercollider/sc3-plugins/issues/89#issuecomment-225690941>, or mute the thread <https://github.com/notifications/unsubscribe/AADTrKjvcJdKvJngoO8BCS_K2dHRz6mtks5qLbbHgaJpZM4Iz0fm>.
> 

******************************************
/* Joshua D. Parmenter
http://www.realizedsound.net/josh/

“Every composer – at all times and in all cases – gives his own interpretation of how modern society is structured: whether actively or passively, consciously or unconsciously, he makes choices in this regard. He may be conservative or he may subject himself to continual renewal; or he may strive for a revolutionary, historical or social palingenesis." - Luigi Nono
*/

**Comment by telephon** [comment]
I think, yes. The plugins are also administrated as in the Quarks, so they can be dependencies of Quarks. Never tried though. @crucialfelix knows?

**Comment by snappizz** [comment]
Right now plugins are independent of quarks. Some quarks say "go install sc3-plugins before you use this" in the documentation, but that's the closest thing we have to quark-plugin dependency.

There's been talk of making plugins a type of quark, but no plans have materialized yet.

**Comment by telephon** [comment]
Ah ok. But what you can do is:
```
if(\BFPanner.asClass.isNil) { 
    Error("Josh Classes Quark requires JoshUGens. Please install sc3plugins.").throw 
};
```

**Comment by telephon** [comment]
A bit heuristic, but this may work also:
```
LanguageConfig.includePaths.any { |x| pathMatch(x +/+ "*").any { |x| x.find("SC3plugins").notNil } };
```

**Comment by crucialfelix** [comment]
Plugins would need to include the compiled binaries for multiple OS so we can't easily make it into a quark.

I think they should just come with supercollider. batteries included.

**Comment by telephon** [comment]
yes, that is better.

**Comment by vivid-synth** [comment]
@crucialfelix Is there currently a migration path for sc plugins that have matured to move into the sc repo?

**Comment by snappizz** [comment]
I have opened an issue at the main repo to continue this discussion.

**Comment by crucialfelix** [comment]
Not moved, but they could be included pre-installed with releases.

**Comment by snappizz** [comment]
Huge thanks to @dotinspace for doing all the work on this issue.
