### ISSUE TITLE
[berlach] Oversampling ugens crash server when using block sizes larger than 64

### ISSUE THREAD

**Issue by timblechmann** [supercollider/sc3-plugins#9]

**Comment by snappizz** [comment]
A 64-sample block size [is very much hardcoded into those ugens](https://github.com/supercollider/sc3-plugins/blob/master/source/BerlachUGens/Oversamp.h). That sucks :(

**Comment by vivid-synth** [comment]
For posterity: this was fixed with https://github.com/supercollider/sc3-plugins/issues/101
